<?php

namespace CarnetVoyage\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    public function getSelectList()
    {
        $liste_pays = $this->getEntityManager()
                ->getRepository('CarnetVoyageMapBundle:Pays')
                ->findAll();
        
        $pays_regions = array();
        
        foreach ($liste_pays as $pays){
            $liste_region = $this->findBy(array ('pays' => $pays->getId()));
            $regions = array();
            foreach ($liste_region as $region){
                $regions[$region->getId()] = $region;
            }
            $pays_regions[$pays->getValeur()] = $regions;
        }
        
        return $pays_regions;
    }

}