<?php

namespace CarnetVoyage\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeVisitableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVisitableRepository extends EntityRepository
{
}