CarnetVoyageMapAcceuil:
    pattern:  /
    defaults: { _controller: CarnetVoyageMapBundle:Map:index, format: json }
    
CarnetVoyageMapVoirPays:
    pattern:  /seeCountry/{id}
    defaults: { _controller: CarnetVoyageMapBundle:Map:seeCountry, format: html }
    requirements:
        format: html|xml
    
CarnetVoyageMapAjouterVoyage:
    pattern:   /newTrip
    defaults:  { _controller: CarnetVoyageMapBundle:Map:newTrip }

CarnetVoyageMapListerVoyage:
    pattern:   /listTrip
    defaults:  { _controller: CarnetVoyageMapBundle:Map:listTrip }
        
CarnetVoyageMapModifierVoyage:
    pattern:   /modifyTrip/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:modifyTrip }
    
CarnetVoyageMapSupprimerVoyage:
    pattern:   /deleteTrip/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:deleteTrip }      
