CarnetVoyageMapAcceuil:
    pattern:  /
    defaults: { _controller: CarnetVoyageMapBundle:Map:index, format: json }
    
CarnetVoyageMapVoirPays:
    pattern:  /see_country/{id}
    defaults: { _controller: CarnetVoyageMapBundle:Map:see_country, format: html }
    requirements:
        format: html|xml
    
CarnetVoyageMapAjouterVoyage:
    pattern:   /new_trip
    defaults:  { _controller: CarnetVoyageMapBundle:Map:new_trip }

CarnetVoyageMapListerVoyage:
    pattern:   /list_trip
    defaults:  { _controller: CarnetVoyageMapBundle:Map:list_trip }
        
CarnetVoyageMapModifierVoyage:
    pattern:   /modify_trip/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:modify_trip }
    
CarnetVoyageMapSupprimerVoyage:
    pattern:   /delete_trip/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:delete_trip }      
