CarnetVoyageMapAcceuil:
    pattern:  /
    defaults: { _controller: CarnetVoyageMapBundle:Map:index, format: json }
    
CarnetVoyageMapVoirPays:
    pattern:  /seeCountry/{id}
    defaults: { _controller: CarnetVoyageMapBundle:Map:seeCountry, format: html }
    requirements:
        format: html|xml
    
CarnetVoyageMapAjouterVoyage:
    pattern:   /newTrip
    defaults:  { _controller: CarnetVoyageMapBundle:Map:newTrip }

CarnetVoyageMapListerVoyage:
    pattern:   /listTrip
    defaults:  { _controller: CarnetVoyageMapBundle:Map:listTrip }

CarnetVoyageMapManagerPhoto:
    pattern:   /managePhoto
    defaults:  { _controller: CarnetVoyageMapBundle:Map:managePhoto }
    
CarnetVoyageMapAjouterPhoto:
    pattern:   /addPhoto
    defaults:  { _controller: CarnetVoyageMapBundle:Map:addPhoto }  
    
CarnetVoyageMapModifierPhoto:
    pattern:   /modifyPhoto/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:modifyPhoto }  
    
CarnetVoyageMapSupprimerPhoto:
    pattern:   /deletePhoto/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:deletePhoto }  

CarnetVoyageMapListerPhotos:
    pattern:   /listPhotos/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:listPhotos }
        
CarnetVoyageMapModifierVoyage:
    pattern:   /modifyTrip/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:modifyTrip }
    
CarnetVoyageMapSupprimerVoyage:
    pattern:   /deleteTrip/{id}
    defaults:  { _controller: CarnetVoyageMapBundle:Map:deleteTrip }      
