parameters:
#    carnet_voyage_map.example.class: CarnetVoyage\MapBundle\Example

services:
#    carnet_voyage_map.example:
#        class: %carnet_voyage_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
